### ISSUE TITLE
Compute orientation of houses

### ISSUE THREAD

**Issue by WerthersEchte** [ISAAKiel/postAAR-python#11]
Orientation of houses is important for differentiating complicated settlement plans. One possibility is the construction with the min bound rect as basis.

**Comment by nmueller18** [comment]
After thinking about it, I do not consider this a necessary option for postAAR anymore. This would be part of post-processing, perhaps of a plugin of its own (there is already [SQL-code](https://archaeology.datastations.nl/file.xhtml?fileId=824831&version=1.0) for it).
